spring.application.name=BankServicesApp

server.port=8080

# Spring Boot Actuator Health Endpoint Configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
