spring.application.name=MultiDatabases

server.port=8080

# Primary Data Source (DB1 - Book Database)
spring.db1.datasource.url=jdbc:h2:mem:bookdb;DB_CLOSE_DELAY=-1
spring.db1.datasource.driverClassName=org.h2.Driver
spring.db1.datasource.username=sa
spring.db1.datasource.password=

# Secondary Data Source (DB2 - Student Database)
spring.db2.datasource.url=jdbc:h2:mem:studentdb;DB_CLOSE_DELAY=-1
spring.db2.datasource.driverClassName=org.h2.Driver
spring.db2.datasource.username=sa
spring.db2.datasource.password=

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
